# -*- coding: utf-8 -*-
"""Дорошенко Родион ПИ-311. Лабораторная работа 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zF6dZcyo-Wy2dWRxJjo1NECnBU5KUmfk
"""

a=5
b=int(input())
c=a*b
print(c)

a=int(input())
b=int(input())
c=(a+b)**2
print(c)

a=15
b=10
c=int(input())
d=(a+b)//c
print(d)

a=int(input())
b=int(input())
c=a**2 + 2*a*b + b**2
print(c)

a=int(input())
b=int(input())
c=int(input())
P=a+b+c
p=P//2
S=(p*(p-a)*(p-b)*(p-c))**0.5
print(P,S)

a=int(input())
b=int(input())
c=(((a**3 + 14)//5)*b)
print(c)

a=int(input())
n=int(input())
b=((a**2)//n)
print(b)

a=float(input())
b=float(input())
c=int(input())
d=int(input())
f=int(input())
g=int(input())
z=a//b
o=c*d
v=f%g
print(z,o,v)

n=int(input())
d=n//86400
h=n//3600
m=n//60
print(d,h,m)

n=int(input())
a=n + n**2 + n**3
print(a)