# -*- coding: utf-8 -*-
"""Дорошенко Родион ПИ-311. Лабораторная работа 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Ph2jrz6m2RV946GUtovOsFSv1hHf4fb
"""

n=int(input())
if n==1:
   print('January')
if n==2:
   print('February')
if n==3:
   print('March')
if n==4:
   print('April')
if n==5:
   print('May')
if n==6:
   print('June')
if n==7:
   print('July')
if n==8:
   print('August')
if n==9:
   print('September')
if n==10:
   print('October')
if n==11:
   print('November')
if n==12:
   print('December')

n=int(input())
if n%2==1:
   print('нечётное')
else:
  print('чётное')

n=int(input())
if n>40:
  print('stonks')
elif n<40:
  print('not stonks')
else:
  print('нет в условии')

n=int(input())
a=n%4
if a==0:
  print('True')
else:
  print('False')

n=int(input())
if n==5 or n==2 or n==3:
  print('простое')
elif n%2==0 or n%3==0 or n%5==0 or n%10==0:print('непростое')
else:print('простое')

n=float(input())
j=float(input())
a=-246
b=-100
c=n/j
if c==3.6 or (j>a and j<b):
  n,j=j,n
  print(n,j)
else:
  print(n,j)

numbers=[]
for i in range(5):
  num = int(input())
  numbers.append(num)


uniq = len(numbers) == len(set(numbers))
chet = sum(1 for num in numbers if num % 2 == 0)
minus = sum(1 for num in numbers if num < 0)
prom = sum(1 for num in numbers if -256 <= num <= 1024)

print(" уникальны:", uniq)
print("четные:", chet)
print("отрицательные:", minus)
print("диапозон:", prom)

a=int(input())
b=int(input())
c=int(input())
n=((a**2+b**3)/(c+3))/4
print(n)
print(n)
if n%2==0:
  print('четное')
else:
  print('нечетое')